./stream_performance_run.sh REMCDockingGPU 1 1
./stream_performance_run.sh REMCDockingGPU 2 1
./stream_performance_run.sh REMCDockingGPU 4 1
./stream_performance_run.sh REMCDockingGPU 5 1
./stream_performance_run.sh REMCDockingGPU 10 1
./stream_performance_run.sh REMCDockingGPU 2 2
./stream_performance_run.sh REMCDockingGPU 4 2
./stream_performance_run.sh REMCDockingGPU 10 2
./stream_performance_run.sh REMCDockingGPU 20 2
